define([
    './address/Address',
    './base/Base',
    './button/Button',
    './checkbox/Checkbox',
    './columns/Column',
    './columns/Columns',
    './container/Container',
    './content/Content',
    './currency/Currency',
    './datagrid/DataGrid',
    './datamap/DataMap',
    './datetime/DateTime',
    './day/Day',
    './editgrid/EditGrid',
    './edittable/EditTable',
    './email/Email',
    './fieldset/Fieldset',
    './file/File',
    './form/Form',
    './html/HTML',
    './hidden/Hidden',
    './location/Location',
    './modaledit/ModalEdit',
    './nested/NestedComponent',
    './number/Number',
    './panel/Panel',
    './password/Password',
    './phonenumber/PhoneNumber',
    './radio/Radio',
    './recaptcha/ReCaptcha',
    './resource/Resource',
    './select/Select',
    './selectboxes/SelectBoxes',
    './signature/Signature',
    './survey/Survey',
    './table/Table',
    './tabs/Tabs',
    './tags/Tags',
    './textarea/TextArea',
    './textfield/TextField',
    './time/Time',
    './tree/Tree',
    './unknown/Unknown',
    './url/Url',
    './well/Well'
], function (AddressComponent, BaseComponent, ButtonComponent, CheckBoxComponent, ColumnComponent, ColumnsComponent, ContainerComponent, ContentComponent, CurrencyComponent, DataGridComponent, DataMapComponent, DateTimeComponent, DayComponent, EditGridComponent, EditTableComponent, EmailComponent, FieldsetComponent, FileComponent, FormComponent, HTMLComponent, HiddenComponent, LocationComponent, ModalEdit, NestedComponent, NumberComponent, PanelComponent, PasswordComponent, PhoneNumberComponent, RadioComponent, ReCaptchaComponent, ResourceComponent, SelectComponent, SelectBoxesComponent, SignatureComponent, SurveyComponent, TableComponent, TabsComponent, TagsComponent, TextAreaComponent, TextFieldComponent, TimeComponent, TreeComponent, UnknownComponent, UrlComponent, WellComponent) {
    'use strict';
    return {
        address: AddressComponent,
        base: BaseComponent,
        button: ButtonComponent,
        checkbox: CheckBoxComponent,
        column: ColumnComponent,
        columns: ColumnsComponent,
        container: ContainerComponent,
        content: ContentComponent,
        currency: CurrencyComponent,
        datagrid: DataGridComponent,
        datamap: DataMapComponent,
        datetime: DateTimeComponent,
        day: DayComponent,
        editgrid: EditGridComponent,
        edittable: EditTableComponent,
        email: EmailComponent,
        fieldset: FieldsetComponent,
        file: FileComponent,
        form: FormComponent,
        hidden: HiddenComponent,
        htmlelement: HTMLComponent,
        location: LocationComponent,
        modaledit: ModalEdit,
        nested: NestedComponent,
        number: NumberComponent,
        panel: PanelComponent,
        password: PasswordComponent,
        phoneNumber: PhoneNumberComponent,
        radio: RadioComponent,
        recaptcha: ReCaptchaComponent,
        resource: ResourceComponent,
        select: SelectComponent,
        selectboxes: SelectBoxesComponent,
        signature: SignatureComponent,
        survey: SurveyComponent,
        table: TableComponent,
        tabs: TabsComponent,
        tags: TagsComponent,
        textarea: TextAreaComponent,
        textfield: TextFieldComponent,
        time: TimeComponent,
        tree: TreeComponent,
        unknown: UnknownComponent,
        url: UrlComponent,
        well: WellComponent
    };
});